version: "3"
services:
  postgres:
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=public
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit/V1_CREATE_DATABASE.SQL:/docker-entrypoint-initdb.d/V1_CREATE_DATABASE.SQL
      